DROP TABLE IF EXISTS suit CASCADE;
DROP TABLE IF EXISTS familier CASCADE;
DROP TABLE IF EXISTS eleve CASCADE;
DROP TABLE IF EXISTS cours CASCADE;
DROP TABLE IF EXISTS baguette CASCADE;
DROP TABLE IF EXISTS prixBois CASCADE;
DROP TABLE IF EXISTS prixCoeur CASCADE;
DROP TABLE IF EXISTS requiert CASCADE;
